### ISSUE TITLE
NAddableOverlay를 지도에서 삭제해도 지도의 OverlayController를 여전히 참조함

### ISSUE THREAD

**Issue by battlecook** [note11g/flutter_naver_map#127]
유용한 라이브러리를 만들어주셔서 감사드립니다

사용중 FIREBASE CRASHLYTICS 에서 PlatformException 을 간헐적으로 보고받아 알려드립니다

정상적으로 동작중에 간헐적으로 발생중에 있습니다

재현경로 확인중에 있습니다

버전: 1.0.2

```
I/flutter (13362): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (13362): PlatformException(error, overlay can't found because it's null, null, java.lang.IllegalArgumentException: overlay can't found because it's null
I/flutter (13362): 	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController.handler(OverlayController.kt:106)
I/flutter (13362): 	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController.$r8$lambda$x3t98W9KAiqviSjw3VmnMZcgiKo(Unknown Source:0)
I/flutter (13362): 	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController$$ExternalSyntheticLambda1.onMethodCall(Unknown Source:2)
I/flutter (13362): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter (13362): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (13362): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter (13362): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (13362): 	at android.os.Handle
I/flutter (13362): 
I/flutter (13362): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
I/flutter (13362): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
I/flutter (13362): <asynchronous suspension>
I/flutter (13362): #2      _NOverlaySender._send (package:flutter_naver_map/src/type/map/overlay/overlay/overlay_sender.dart:21:12)
I/flutter (13362): <asynchronous suspension>
I/flutter (13362): #3      _NOverlaySender._set (package:flutter_naver_map/src/type/map/overlay/overlay/overlay_sender.dart:26:5)
I/flutter (13362): <asynchronous suspension>
I/flutter (13362): ----------------------------------------------------
```

**Comment by note11g** [comment]
지도에 추가가 가능한 오버레이(NAddableOverlay의 서브클래스들)는, 지도에서 사라진 후에 함수를 실행하게 되면 해당 예외가 발생합니다.
아마, 지도에서 지운 오버레이에 setXX 함수를 실행시켜 발생하는 오류로 보입니다. (따로 라이브러리가 해제를 하지 않았기 때문)
이는 버그로 보이며, 빠른 시일 내 수정토록 하겠습니다.

**Comment by note11g** [comment]
*`NAddableOverlay` 재사용 불가 문제
