### ISSUE TITLE
PlatformException(error, overlay can't found because it's null, null, Java, Lang. IllegalArgumentException: overlay can't found because it's null

### ISSUE THREAD

**Issue by baekjungkim** [note11g/flutter_naver_map#274]
화면에 처음 진입시에는 괜찮은데 화면 재 진입시에 해당 에러가 발생합니다(가끔 처음 진입시에도 에러날때 있음)

```
E/MethodChannel#flutter_naver_map_overlay#5(25655): Failed to handle method call
E/MethodChannel#flutter_naver_map_overlay#5(25655): java.lang.IllegalArgumentException: overlay can't found because it's null
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController.handler(OverlayController.kt:109)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController.$r8$lambda$9L2aH7F40vWkimuQuN2mrtZZ86c(Unknown Source:0)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController$$ExternalSyntheticLambda0.onMethodCall(D8$$SyntheticClass:0)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at android.app.ActivityThread.main(ActivityThread.java:8810)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/MethodChannel#flutter_naver_map_overlay#5(25655): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Debug 모드로 에러가 잡히고(자세하게 어디서 잡히는지는 모름..) 계속(F5) 버튼을 누르면 아래 에러가 다시 발생하고
클러스터와 함께 마커가 출력이 됩니다.

```
[Error] PlatformException(error, overlay can't found because it's null, null, Java, Lang. IllegalArgumentException: overlay can't found because it's null
at dev.notell.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController.handler(OverlayController.kt:109)
at dev.notell. flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController.$8$1ambda$9LZaH7F40vIkimuQuN2mrtZZ86c(Unknown Source:0)
at dev.notell.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController$$ExternalSyntheticLambda0.onMethodCall(D8S$SyntheticClass:0)
at 1o.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessageMethodchannel. java: 267)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java: 292)
at 1o.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueueS0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java: 319)
at 1o.flutter.embedding.engine.dart.DartMessengerS$ExternalSyntheticLambda0.run(D8$SSyntheticClass:0)
at android.os.Handler.handlecallback(Handler.java: 942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper. loopOnce(Looper.java: 226)
at android.os.Looper.loop(Looper.java: 313)
at android.app.ActivityThread.main(ActivityThread.java: 8810)
at java. lang.reflect.Method. invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Runtimelnit.java: 604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 1067)
#O
#1
#2
StandardMethodCodec. decodeEnvelope (package: flutter/src/services/message_codecs.dart:648:7)
MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
‹asynchronous suspension>
_NOverlaySender._send (package: flutter_naver_map/src/type/map/overlay/overlay/overlay_sender. dart: 24:19)
```

**Comment by note11g** [comment]
안녕하세요, 오류를 제보해주셔서 감사드립니다.
재현조건 조사를 위해, 해당 오류를 재현할 수 있는 최소 재현 코드를 부탁드려도 괜찮을까요?

**Comment by baekjungkim** [comment]
> 안녕하세요, 오류를 제보해주셔서 감사드립니다. 재현조건 조사를 위해, 해당 오류를 재현할 수 있는 최소 재현 코드를 부탁드려도 괜찮을까요?

```
final markerList = await fetchMarkerList(userId);

final clusterMarker = [];

for(final marker in markerList) {
  final response = await http.get(Uri.parse(marker.imageUrl));
  final imageMemory = response.bodyBytes;
  final imageIcon = await NOverlayImage.fromByteArray(imageMemory);
  final position = NLatLng(marker.latitude,marker.longitude);

  final cluster = NClusterableMarker(
    id: marker.id,
    position: position,
    icon: imageMarker,
  )

  clusterMarker.add(cluster);
}

await controller.addOverlayAll(clusterMarker.toSet());

```

이렇게 되어있습니다.  안드로이드에서만 테스트 해보았습니다

**Comment by note11g** [comment]
@baekjungkim "클러스터와 마커가 함께 보여진다"고 말씀해주셨는데, 혹시 해당 현상이 일어나는 스크린샷을 제공해주실 수 있으실까요?

**Comment by baekjungkim** [comment]
> @baekjungkim "클러스터와 마커가 함께 보여진다"고 말씀해주셨는데, 혹시 해당 현상이 일어나는 스크린샷을 제공해주실 수 있으실까요?

@note11g 마커는 제대로 출력이 된다는 말이었습니다. 안드로이드에서 디버그에서 실행시 에러가 발생됩니다.

**Comment by ji3537** [comment]
저도 같은 문제입니다.
전부 기본마커로 해보니 다 정상 작동하는데
클러스터만 하면 지도가 멈추는데
note11님
부탁드립니다 ^^
언제쯤 괜찮아질지 몹시 궁금합니다
즐거운 저녁에 비까지 내리니
괜히 기분 좋네요

**Comment by hisoft-dev** [comment]
(1)

**Comment by hisoft-dev** [comment]
안녕하세요. 
훌륭한 라이브러리 공개해 주셔서 잘 사용하고 있습니다.
버전 1.3.0 사용 중 에러가 발견되었습니다.

NClusterbaleMarker를 사용해서 
마커 클러스터링 기능을 구현 했고,
지도에 마커를 삭제 후 추가하는 코드가 있습니다.

clearOverlays() 호출시 아래와 같은 에러가 발생합니다.
Android 에서만 에러가 발생하고 iOS에서는 발생하지 않습니다.

아래 에러가 수정 되어야 앱을 배포할 수 있는 상황이라…ㅠㅠ
빠른 버그 패치 부탁드립니다.

감사합니다.

=========================================

(1) 지도 소스
_naverMapController?.clearOverlays();
_naverMapController?.addOverlayAll(_markers.toSet());


(2) 에러 메시지

package:flutter_naver_map/src/controller/overlay/overlay_controller_impl.dart
Not Added or Already Deleted this overlay : NOverlayInfo(type: NOverlayType.clusterableMarker, id: 01rhZScYOLQQ4K2cIngo)
…
java.lang.IllegalArgumentException: overlay can't found because it's null
    	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController.handler(OverlayController.kt:109)
    	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController.$r8$lambda$x3t98W9KAiqviSjw3VmnMZcgiKo(Unknown Source:0)
    	at dev.note11.flutter_naver_map.flutter_naver_map.controller.overlay.OverlayController$$ExternalSyntheticLambda1.onMethodCall(Unknown Source:2)
    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
    	at android.os.Handler.handleCallback(Handler.java:938)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loop(Looper.java:247)
    	at android.app.ActivityThread.main(ActivityThread.java:8676)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by jisu-kroffle** [comment]
저도 위 오류를 모두 경험하고, overlay의 null exception과 관련된 코드를 다음과 같이 수정하여
오류 없이 작동하도록 만들었습니다.

이 방법은 임시 방편일 뿐이며, 정확하고 안전하지 않습니다

`/flutter_naver_map/android/src/main/kotlin/dev/note11/flutter_naver_map/flutter_naver_map/controller/overlay/OverlayController.kt`

109번째 라인

```
private fun handler(call: MethodCall, result: MethodChannel.Result) {
    val query = NOverlayQuery.fromQuery(call.method)
    Log.d("query of NOverlayInfo", query.toString());
    val overlay = getOverlay(query.info)

//        requireNotNull(overlay) { "overlay can't found because it's null" }

    if (overlay != null) {
        Log.d("getOverlay", overlay.toString());

        val isInvokedOnCommonOverlay =
            handleOverlay(overlay, query.methodName, call.arguments, result)

        if (!isInvokedOnCommonOverlay) {
            val overlayHandleFunc = when (query.info.type) {
                NOverlayType.MARKER -> this::handleMarker
                NOverlayType.INFO_WINDOW -> this::handleInfoWindow
                NOverlayType.CIRCLE_OVERLAY -> this::handleCircleOverlay
                NOverlayType.GROUND_OVERLAY -> this::handleGroundOverlay
                NOverlayType.POLYGON_OVERLAY -> this::handlePolygonOverlay
                NOverlayType.POLYLINE_OVERLAY -> this::handlePolylineOverlay
                NOverlayType.PATH_OVERLAY -> this::handlePathOverlay
                NOverlayType.MULTIPART_PATH_OVERLAY -> this::handleMultipartPathOverlay
                NOverlayType.ARROWHEAD_PATH_OVERLAY -> this::handleArrowheadPathOverlay
                NOverlayType.LOCATION_OVERLAY -> this::handleLocationOverlay
                NOverlayType.CLUSTERABLE_MARKER -> this::handleClusterableMarker
            }
            overlayHandleFunc(overlay, query.methodName, call.arguments, result)
        }
    }
}
```

`/flutter_naver_map/lib/src/type/map/overlay/overlay/overlay_sender.dart`

21번째 라인

```
for (final overlayController in _overlayControllers) {
  lastValue = await overlayController.invokeMethod(query, messageable).catchError((e) {});
}
```


위 코드가 적용된 fork repo는 다음과 같이 사용할 수 있습니다

`pubspec.yaml`
```
# flutter_naver_map: ^1.3.0+1
flutter_naver_map:
  git:
    url: https://github.com/Jisup/flutter_naver_map.git
    ref: main
```


올바르고 안전한 해결 방법으로, 이 문제가 빠르게 해결되길 바랍니다.

**Comment by Jisup** [comment]
저도 위 오류를 모두 경험하고, overlay의 null exception과 관련된 코드를 다음과 같이 수정하여
오류 없이 작동하도록 만들었습니다.

이 방법은 임시 방편일 뿐이며, 정확하고 안전하지 않습니다

`/flutter_naver_map/android/src/main/kotlin/dev/note11/flutter_naver_map/flutter_naver_map/controller/overlay/OverlayController.kt`

109번째 라인

```
private fun handler(call: MethodCall, result: MethodChannel.Result) {
    val query = NOverlayQuery.fromQuery(call.method)
    Log.d("query of NOverlayInfo", query.toString());
    val overlay = getOverlay(query.info)

//        requireNotNull(overlay) { "overlay can't found because it's null" }

    if (overlay != null) {
        Log.d("getOverlay", overlay.toString());

        val isInvokedOnCommonOverlay =
            handleOverlay(overlay, query.methodName, call.arguments, result)

        if (!isInvokedOnCommonOverlay) {
            val overlayHandleFunc = when (query.info.type) {
                NOverlayType.MARKER -> this::handleMarker
                NOverlayType.INFO_WINDOW -> this::handleInfoWindow
                NOverlayType.CIRCLE_OVERLAY -> this::handleCircleOverlay
                NOverlayType.GROUND_OVERLAY -> this::handleGroundOverlay
                NOverlayType.POLYGON_OVERLAY -> this::handlePolygonOverlay
                NOverlayType.POLYLINE_OVERLAY -> this::handlePolylineOverlay
                NOverlayType.PATH_OVERLAY -> this::handlePathOverlay
                NOverlayType.MULTIPART_PATH_OVERLAY -> this::handleMultipartPathOverlay
                NOverlayType.ARROWHEAD_PATH_OVERLAY -> this::handleArrowheadPathOverlay
                NOverlayType.LOCATION_OVERLAY -> this::handleLocationOverlay
                NOverlayType.CLUSTERABLE_MARKER -> this::handleClusterableMarker
            }
            overlayHandleFunc(overlay, query.methodName, call.arguments, result)
        }
    }
}
```

`/flutter_naver_map/lib/src/type/map/overlay/overlay/overlay_sender.dart`

21번째 라인

```
for (final overlayController in _overlayControllers) {
  lastValue = await overlayController.invokeMethod(query, messageable).catchError((e) {
    print(e);
  });
}
```


위 코드가 적용된 fork repo는 다음과 같이 사용할 수 있습니다

`pubspec.yaml`
```
# flutter_naver_map: ^1.3.0+1
flutter_naver_map:
  git:
    url: https://github.com/Jisup/flutter_naver_map.git
    ref: main
```


올바르고 안전한 해결 방법으로, 이 문제가 빠르게 해결되길 바랍니다.

**Comment by note11g** [comment]
> 저도 위 오류를 모두 경험하고, overlay의 null exception과 관련된 코드를 다음과 같이 수정하여 오류 없이 작동하도록 만들었습니다.
> 
> 이 방법은 임시 방편일 뿐이며, 정확하고 안전하지 않습니다
> 
> `/flutter_naver_map/android/src/main/kotlin/dev/note11/flutter_naver_map/flutter_naver_map/controller/overlay/OverlayController.kt`
> 
> 109번째 라인
> 
> ```
> private fun handler(call: MethodCall, result: MethodChannel.Result) {
>     val query = NOverlayQuery.fromQuery(call.method)
>     Log.d("query of NOverlayInfo", query.toString());
>     val overlay = getOverlay(query.info)
> 
> //        requireNotNull(overlay) { "overlay can't found because it's null" }
> 
>     if (overlay != null) {
>         Log.d("getOverlay", overlay.toString());
> 
>         val isInvokedOnCommonOverlay =
>             handleOverlay(overlay, query.methodName, call.arguments, result)
> 
>         if (!isInvokedOnCommonOverlay) {
>             val overlayHandleFunc = when (query.info.type) {
>                 NOverlayType.MARKER -> this::handleMarker
>                 NOverlayType.INFO_WINDOW -> this::handleInfoWindow
>                 NOverlayType.CIRCLE_OVERLAY -> this::handleCircleOverlay
>                 NOverlayType.GROUND_OVERLAY -> this::handleGroundOverlay
>                 NOverlayType.POLYGON_OVERLAY -> this::handlePolygonOverlay
>                 NOverlayType.POLYLINE_OVERLAY -> this::handlePolylineOverlay
>                 NOverlayType.PATH_OVERLAY -> this::handlePathOverlay
>                 NOverlayType.MULTIPART_PATH_OVERLAY -> this::handleMultipartPathOverlay
>                 NOverlayType.ARROWHEAD_PATH_OVERLAY -> this::handleArrowheadPathOverlay
>                 NOverlayType.LOCATION_OVERLAY -> this::handleLocationOverlay
>                 NOverlayType.CLUSTERABLE_MARKER -> this::handleClusterableMarker
>             }
>             overlayHandleFunc(overlay, query.methodName, call.arguments, result)
>         }
>     }
> }
> ```
> 
> `/flutter_naver_map/lib/src/type/map/overlay/overlay/overlay_sender.dart`
> 
> 21번째 라인
> 
> ```
> for (final overlayController in _overlayControllers) {
>   lastValue = await overlayController.invokeMethod(query, messageable).catchError((e) {
>     print(e);
>   });
> }
> ```
> 
> 위 코드가 적용된 fork repo는 다음과 같이 사용할 수 있습니다
> 
> `pubspec.yaml`
> 
> ```
> # flutter_naver_map: ^1.3.0+1
> flutter_naver_map:
>   git:
>     url: https://github.com/Jisup/flutter_naver_map.git
>     ref: main
> ```
> 
> 올바르고 안전한 해결 방법으로, 이 문제가 빠르게 해결되길 바랍니다.

해당 방법은 로그에서 오류가 나지 않을 뿐, 수행되는 동작은 동일합니다.
근본적인 해결방법이 아닐 뿐더러, 잘못된 코드에도 개발자가 대응하지 못하게 되는 현상이 발생할 수 있으므로, 해당 코멘트를 숨김처리하였습니다.
양해 부탁드립니다.

**Comment by coordlink-chiduk** [comment]
@note11g 안녕하세요 해당 이슈는 아직 해결이 안된건가요?

**Comment by note11g** [comment]
@coordlink-chiduk 재현이 되지 않고 있어, 더 조사가 필요한 상황입니다.
