### ISSUE TITLE
Android Platform에서 현위치 사용시 앱 강제종료 현상

### ISSUE THREAD

**Issue by cyb9701** [note11g/flutter_naver_map#36]
안드로이드 기기에서 네이버 지도 화면 진입 시 앱이 튕기는 현상이 있습니다.

위치 트레킹 모드를 `initLocationTrackingMode: LocationTrackingMode.None` 으로 하면 튕기지 않지만
다른 설정으로 변경하면 튕기는 현상이 있습니다.

- **오류 로그**
```
D/AndroidRuntime( 5465): Shutting down VM
E/AndroidRuntime( 5465): FATAL EXCEPTION: main
E/AndroidRuntime( 5465): Process: com.billyo.billyo_app, PID: 5465
E/AndroidRuntime( 5465): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~6VjRkaO2ssrFNi4o9uIwIQ==/com.billyo.billyo_app-C9SPxQ24TITOlxKtc0-Dlw==/base.apk)
E/AndroidRuntime( 5465): 	at com.naver.maps.map.util.FusedLocationSource$b$1.onConnected(SourceFile:125)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.internal.zak.zad(com.google.android.gms:play-services-base@@18.1.0:11)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.api.internal.zabe.zab(com.google.android.gms:play-services-base@@18.1.0:3)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.api.internal.zaaw.zaC(com.google.android.gms:play-services-base@@18.1.0:11)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.api.internal.zaaw.zag(com.google.android.gms:play-services-base@@18.1.0:4)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.api.internal.zabi.onConnected(com.google.android.gms:play-services-base@@18.1.0:2)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.api.internal.zat.onConnected(com.google.android.gms:play-services-base@@18.1.0:1)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.internal.zah.onConnected(com.google.android.gms:play-services-base@@18.1.0:1)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.internal.zzf.zzd(com.google.android.gms:play-services-basement@@18.1.0:10)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.1.0:4)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.1.0:3)
E/AndroidRuntime( 5465): 	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.1.0:31)
E/AndroidRuntime( 5465): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5465): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 5465): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 5465): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 5465): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5465): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 5465): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/TRuntime.CctTransportBackend( 5465): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
W/FirebaseCrashlytics( 5465): Timeout exceeded while awaiting app exception callback from Analytics listener.
I/TRuntime.CctTransportBackend( 5465): Status Code: 200
I/Process ( 5465): Sending signal. PID: 5465 SIG: 9
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"150","method":"getMemoryUsage","params":{"isolateId":"isolates/3461519088935227"}}
```

**Comment by note11g** [comment]
https://developers.google.com/android/guides/releases?hl=ko#october_13_2022
해당 문제와 관련 있어보입니다.
빠른 시일내 조치하도록 하겠습니다.

**Comment by note11g** [comment]
@cyb9701 혹시 location 권한을 AndroidManifest.xml에 선언해주셨는지 궁금합니다.

**Comment by note11g** [comment]
@cyb9701 
혹시 com.google.android.gms:play-services-location 종속성을 따로 설정하셨을까요?
그렇다면 사용하시는 버전을 알려주세요.

**Comment by note11g** [comment]
현재 네이버맵 SDK 3.16.1과 com.google.android.gms:play-services-location 20버전 이상의 호환성이 문제가 있는 것으로 보입니다.
네이버맵에서 지원하기 전까지는 flutter-naver-map에서 문제 없음이 확인된 18.0.0 버전을 사용하시는 것을 권장해드립니다.

네이버측으로부터 지원에 대한 답변이 공식적으로 오면 코멘트 자세히 남기도록 하겠습니다. 감사합니다.

다음은 18.0.0을 사용하도록 하는 예시입니다.
```gradle 
// build.gradle(:app)
    dependencies {
        implementation 'com.google.android.gms:play-services-location:18.0.0'

        // 적용이 되지 않아, 강제하려면 다음과 같이 시도하세요
       configurations.all {
            resolutionStrategy {
                force 'com.google.android.gms:play-services-location:18.0.0'
            }
        }
    }
```

**Comment by note11g** [comment]
1.0에서 임시방편으로 force 이용하여 수정하였습니다.
감사합니다.

**Comment by cyb9701** [comment]
@note11g 
제 프로젝트에서 `com.google.android.gms:play-services-location` 종속성을 따로 지정은 하지 않은 상황입니다.
그리고 `flutter_naver_map: ^0.10.6` 을 사용 중입니다.

찾아보니깐 패키지들의 `com.google.android.gms:play-services-location` 종속성 버전이 다를 경우 발생할 수도 있는 오류라고도 합니다. `geolocator` 패키지에서는 21.0.1 버전을 사용 중인데 이거에 대한 문제는 아닌가요?

제가 따로 네이버 지도 패키지나 위치 종속성을 건들인적이 없는데 갑자기 발생한 오류라서 정확한 원인을 찾기가 힘드네요...😭

**Comment by note11g** [comment]
@cyb9701 한번 fix된 1.0 버전 사용해보시겠어요? branch dev_preview에서 보실 수 있습니다.

**Comment by cyb9701** [comment]
@note11g 
1.0 버전에서 `initLocationTrackingMode` 매개변수는 어떤걸로 변경되었을 까요?
아직까지 정확한 문서가 없어서 못찾고 있는 상황입니다!

**Comment by note11g** [comment]
@cyb9701 onMapReady에서, `controller.setLocationTrackingMode(NLocationTrackingMode mode);` 을 통해 지정하실 수 있습니다.

**Comment by cyb9701** [comment]
@note11g  감사합니다! 테스트 진행 후 결과 전달드리겠습니다

**Comment by cyb9701** [comment]
@note11g 
이번에는 geolocator 오류가 발생하네요

```
E/AndroidRuntime( 6572): 	at com.baseflow.geolocator.location.FusedLocationClient.isLocationServiceEnabled(FusedLocationClient.java:135)
E/AndroidRuntime( 6572): 	at com.baseflow.geolocator.location.GeolocationManager.isLocationServiceEnabled(GeolocationManager.java:45)
E/AndroidRuntime( 6572): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onIsLocationServiceEnabled(MethodCallHandlerImpl.java:138)
E/AndroidRuntime( 6572): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:62)
E/AndroidRuntime( 6572): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 6572): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 6572): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 6572): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 6572): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 6572): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6572): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 6572): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 6572): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 6572): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6572): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 6572): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by note11g** [comment]
@cyb9701 example에서 geolocator을 사용하는 코드를 변경한게 있으신지 궁금합니다.

**Comment by cyb9701** [comment]
@note11g  따로 변경한건 없습니다!

**Comment by note11g** [comment]
@cyb9701 재현을 위해 안드로이드 버전, 단말 정보 부탁드립니다.

**Comment by yoojin282** [comment]
저는 일단 geolocator 버전을 8.2.1 으로 낮춰서 사용하니 정상작동합니다.
geolocator  9.0.0 버전부터 play-services-location:21.0.1 사용하여 충돌하는거 같네요

**Comment by cyb9701** [comment]
@yoojin282  정상 작동 확인했습니다! 감사합니다!

**Comment by note11g** [comment]
dev preview 1.0.0에서는 `geolocator: ^9.0.2`을 사용하고 있습니다.
제 테스트 환경에서는 이슈 재현이 되지 않고 있습니다. 
@cyb9701 재현을 위한 구체적인 정보 부탁드려도 될까요?

**Comment by cyb9701** [comment]
@note11g 
구체적인 정보가 너무 광범위해서 어떤 정보를 드려야할지 모르겠네요.
우선 기기 정보 같은 경우는 디버그 모드에서 가상환경과 실제 기기에서도 문제가 발생했고
릴리즈 모드에서도 모든 안드로이드 기종의 휴대폰에서 위와 같은 문제가 발생했었습니다.

**Comment by yoojin282** [comment]
@note11g 
dependencies 에

geolocator: ^9.0.2
flutter_naver_map:
  git:
    url: https://github.com/note11g/flutter_naver_map.git
    ref: dev_preview

두 라이브러리 추가후  네이버맵 화면 띄운 화면에서 geolocator 로 현재위치 가져오려하면 에러 발생하네요.

**Comment by note11g** [comment]
0.10.x 버전에서는 해당 이슈를 수정하지 않았습니다.
다만, 1.0.0-dev2(aa65cc11af8ff94b0eed1a556260a8bb521987be)에서는 해당 이슈 수정하였습니다.

감사합니다. 추후, 0.10.x 버전에 수정이 완료되면 다시 코멘트드리도록 하겠습니다.

**Comment by note11g** [comment]
0.10대 버전은, [0.10.7](https://pub.dev/packages/flutter_naver_map/versions/0.10.7) 에서 수정되었습니다.
