### ISSUE TITLE
android 2회차 실행시 느리게 부팅되는 현상이 있습니다.

### ISSUE THREAD

**Issue by MinJun-chl** [note11g/flutter_naver_map#52]
```

W/OkHttp  (28525): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  (28525): 	at java.lang.Class.getMethod(Class.java:2103)
W/OkHttp  (28525): 	at java.lang.Class.getDeclaredMethod(Class.java:2081)
W/OkHttp  (28525): 	at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  (28525): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  (28525): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  (28525): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  (28525): 	at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  (28525): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  (28525): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  (28525): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  (28525): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  (28525): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  (28525): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
W/OkHttp  (28525): 	at com.naver.maps.map.internal.http.a.a(SourceFile:27)
W/OkHttp  (28525): 	at com.naver.maps.map.internal.http.NativeHttpRequest.<clinit>(SourceFile:35)
W/OkHttp  (28525): 	at java.lang.Runtime.nativeLoad(Native Method)
W/OkHttp  (28525): 	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
W/OkHttp  (28525): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
W/OkHttp  (28525): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
W/OkHttp  (28525): 	at java.lang.System.loadLibrary(System.java:1656)
W/OkHttp  (28525): 	at com.getkeepsafe.relinker.SystemLibraryLoader.loadLibrary(SystemLibraryLoader.java:25)
W/OkHttp  (28525): 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:163)
W/OkHttp  (28525): 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
W/OkHttp  (28525): 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
W/OkHttp  (28525): 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
W/OkHttp  (28525): 	at com.naver.maps.map.internal.a.a(SourceFile:48)
W/OkHttp  (28525): 	at com.naver.maps.map.renderer.MapRenderer.<clinit>(SourceFile:23)
W/OkHttp  (28525): 	at com.naver.maps.map.MapView.a(SourceFile:183)
W/OkHttp  (28525): 	at com.naver.maps.map.MapView.<init>(SourceFile:83)
W/OkHttp  (28525): 	at dev.note11.flutter_naver_map.flutter_naver_map.view.NaverMapView.<init>(NaverMapView.kt:35)
W/OkHttp  (28525): 	at dev.note11.flutter_naver_map.flutter_naver_map.view.NaverMapViewFactory.create(NaverMapViewFactory.kt:30)
W/OkHttp  (28525): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
W/OkHttp  (28525): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
W/OkHttp  (28525): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
W/OkHttp  (28525): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
W/OkHttp  (28525): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/OkHttp  (28525): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/OkHttp  (28525): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/OkHttp  (28525): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/OkHttp  (28525): 	at android.os.Handler.handleCallback(Handler.java:938)
W/OkHttp  (28525): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/OkHttp  (28525): 	at android.os.Looper.loopOnce(Looper.java:226)
W/OkHttp  (28525): 	at android.os.Looper.loop(Looper.java:313)
W/OkHttp  (28525): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
W/OkHttp  (28525): 	at java.lang.reflect.Method.invoke(Native Method)
W/OkHttp  (28525): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
W/OkHttp  (28525): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)


```

기능은 문제 없이 수행되나 android 각종 기기에서 해당 로그를 뱉으며 느리게 부팅되는 현상이 있습니다.
사용 버전은 ^1.0.0-dev.8입니다.

**Comment by note11g** [comment]
@MinJun-chl 

안녕하세요. 먼저, 이슈를 제보해주셔서 감사드립니다.
재현을 위해, 2회차 실행이 정확히 어떻게 실행을 하는 것인지 순차적으로 알려주실 수 있을까요?

**Comment by MinJun-chl** [comment]
1. 기존에 앱이 설치된 경우 run main.dart를 통해 build를 진행합니다.
2. 기존에 앱이 설치되어있지 않은 경우, run main.dart를 통해 한 번 build를 진행한 뒤, 종료 후 다시 run하면 발생합니다.

**Comment by note11g** [comment]
@MinJun-chl 
재현단말 정보도 부탁드릴 수 있을까요?

**Comment by MinJun-chl** [comment]
<img width="554" alt="스크린샷 2023-03-15 오후 2 32 38" src="https://user-images.githubusercontent.com/121079176/225216278-b728fee2-28c8-45aa-b0f3-060c2ed15e28.png">
Emulator의 정보는 위와 같고
실제 단말은 갤럭시 노트 10입니다.

**Comment by note11g** [comment]
@MinJun-chl 해당 현상은 OkHttp3 Android 라이브러리에 의해 발생하는 것으로 보입니다.
에뮬레이터에서는 재현에 실패하였고, 노트 10 단말은 없어 발생 조건을 찾지 못하였습니다.

다음 단계를 따라 확인해주시기 바랍니다.
1. API Level 33인 에뮬레이터에서 해당 오류가 발생하는지 여부
2. 노트 10의 API Level이 30인지 여부
3. 다른 라이브러리가 OkHttp3를 사용하는지 여부

해당 이슈 관련 정보는 다음 [링크](https://stackoverflow.com/questions/69326854/unable-to-load-android-socket-classes-java-lang-nosuchmethodexception-com-andro)에서 확인하였습니다.

**Comment by MinJun-chl** [comment]
1. API level 33인 에뮬레이터에서 동일하게 발생합니다. 사진 첨부합니다.
<img width="554" alt="스크린샷 2023-03-15 오후 5 33 52" src="https://user-images.githubusercontent.com/121079176/225252128-75970f48-ef17-4c40-b1e7-2fa66e7a1430.png">
2. 노트 10은 Android 12, API Level 31입니다.
3. 다른 라이브러리에서 OkHttp3을 사용하지 않습니다.

**Comment by MinJun-chl** [comment]
이 현상은 navermap과는 관련이 없는 현상으로 확인되었습니다.
flutter_tools의 DevFs관련 이슈입니다. Close합니다.

**Comment by note11g** [comment]
@MinJun-chl 괜찮으시다면 관련 링크 부탁드릴 수 있을까요?
